#!/usr/bin/python

import sys
sys.path.append('/usr/local/lib/python')

from thinkpad.OSD import OSD

def main():
	osd = OSD()
	try:
		n = sys.argv.index('--')
		osd.text = ' '.join(sys.argv[n+1:])
		for i in range(1, n):
			arg = sys.argv[i]
			j = arg.index('=')
			if j:
				setattr(osd, arg[0:j].strip('-'), arg[j+1:])
	except:
		osd.text = ' '.join(sys.argv[1:])
	osd.show()

main()
